apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuck-norris-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: chuck-norris
  template:
    metadata:
      labels:
        app: chuck-norris
    spec:
      containers:
      - name: chuck-norris
        image: kessie/chuck-norris
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chuck-norris-service
spec:
  selector:
    app: chuck-norris
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000


